// functions/ops/merge.js — fold the loser account into the survivor.
//
// graduateAccountData is a RENAME into a FREE uid (it hard-fails on an
// existing target). Merging into a LIVE account means every moved path can
// collide, so this builds a write-set with an explicit rule per family and a
// conflict report for everything a human should see before pressing execute.
// Family rules and their rationale: spec §7 (D1-D4); the Telegram repoint that
// makes "link via merge" possible at all: §8.
//
// Reads happen at PREVIEW time through deps — not from a cached snapshot —
// because a destructive write must not be planned against minutes-old state.
//
// `writes` is the PREVIEW set: what an operator approves, and a superset of
// what actually goes on the wire. rootUpdate drops a null that sits under an
// already-nulled ancestor as a redundant delete, so applyMergePlan sends fewer
// keys than this returns. That is correct for a loss report — the ancestor
// delete covers them — but nothing here may be labelled "what will be written".
//
// ANTI-DRIFT: the loser-side residue null-set is generated by
// crossRefRenderers (telegram-auth.js), the ONE enumerator expunge and
// graduation already share. Merge is its third consumer. A new residue family
// belongs THERE, never in this file — the parity test in
// test/ops-merge.test.js is what enforces that.
import { rootUpdate } from '../telegram-shared.js';
import { crossRefRenderers, OWN_MAILBOXES } from '../telegram-auth.js';
import { canvasPeers } from './project.js';
// The ONE Telegram mapping write-block (and the ONE teardown), shared with
// ops/purge.js. Both READ telegramUsers/{tgId} before touching it — see
// telegram-link-write.js for why a global key must never be written unread.
import { buildLinkWrites, buildMappingTeardown } from '../telegram-link-write.js';

/** Transient: a knock or a call is stale within seconds, and merging call state resurrects stuck calls (D3). */
export const DROP_MAILBOXES = ['knocks', 'calls'];
/**
 * Durable: a pending invite, or a revocation that blocks re-following, is real
 * state (D3). Derived from the shared list rather than re-typed, so a seventh
 * mailbox added to OWN_MAILBOXES lands here automatically — the safe default,
 * since unioning a family that turns out to be transient is recoverable and
 * dropping one that turns out to be durable is not.
 */
export const UNION_MAILBOXES = OWN_MAILBOXES.filter((box) => !DROP_MAILBOXES.includes(box));

/**
 * The canvas children a move carries. `strokes` is deliberately ABSENT:
 * canvases/{pair}/strokes is the only unbounded node in the database and must
 * never enter a read or an update payload, so a merged canvas keeps its
 * settings and loses its drawing — reported in the loss report so the operator
 * sees it before approving. `drawing`, `presence`, `clearRequest` and
 * `screenshotRequest` are live-session state (the D3 transient argument) and
 * are dropped with it.
 *
 * Exported so audit.js's pre-image capture reads exactly this same field set
 * for a destroyed canvas — one list, not a hand-copied duplicate that could
 * silently drift (functions/test/ops-audit.test.js has the parity test).
 */
export const CANVAS_CARRIED = ['bg'];

/** Canvas keys are SORTED uid pairs. @param {string} a @param {string} b */
const canvasKeyFor = (a, b) => [a, b].sort().join('_');

/**
 * @param {import('../telegram-link-write.js').ReadDeps} deps
 * @param {{
 *   loserUid: string,
 *   survivorUid: string,
 *   adoptGroupNames?: string[],
 *   telegramRepoint?: boolean,
 *   canvasKeys?: string[],
 *   now: number,
 * }} opts
 * @returns {Promise<import('./types.js').WritePlan>}
 */
export async function buildMergePlan(deps, opts) {
  const { loserUid: L, survivorUid: S, now } = opts;
  if (L === S) throw new Error('merge: loser and survivor are the same uid');
  const adopt = new Set(opts.adoptGroupNames || []);
  // The shallow canvas key list is the only way to learn which canvases exist
  // without reading a node whose strokes child is unbounded — but it is the one
  // input that comes from the SNAPSHOT rather than the live re-read, so treat
  // it as best-available, never as authoritative: the canvas block below stays
  // safe when it is stale. Omitting it leaves canvases untouched (recoverable
  // residue) rather than deleting drawings that were never moved.
  const canvasKeys = opts.canvasKeys || [];
  const existingCanvases = new Set(canvasKeys);

  const [loser, survivor, loserPrefs, survivorPrefs, loserTokens, loserPendingInvites] = await Promise.all([
    deps.getVal(`users/${L}`),
    deps.getVal(`users/${S}`),
    deps.getVal(`userPrefs/${L}`),
    deps.getVal(`userPrefs/${S}`),
    deps.getVal(`pushTokens/${L}`),
    // The enumerator needs the loser's pending-invite gids to null their
    // by-group sweep entries; the mailbox union below re-reads the same node
    // through its uniform per-box loop.
    deps.getVal(`pendingInvites/${L}`),
  ]);
  if (!loser) throw new Error(`merge: no account at users/${L}`);
  if (!survivor) throw new Error(`merge: no account at users/${S} — use graduateAccountData for a free target`);

  /** @type {Record<string, unknown>} */
  const writes = {};
  /** @type {import('./types.js').Conflict[]} */
  const conflicts = [];
  /** @type {string[]} */
  const losses = [];
  /** @type {(kind: string, path: string, detail: string, resolution: string) => void} */
  const conflict = (kind, path, detail, resolution) => conflicts.push({ kind, path, detail, resolution });

  // Every repointed peer backref carries this. Without it `followers/{S}` would
  // be written as null — a DELETE — and every peer who followed only the loser
  // would silently lose the contact, with no conflict and no loss line. An
  // account with no share code cannot be followed at all, so it is not a merge
  // target; refuse rather than build a plan whose loss report is a lie.
  const survivorCode = survivor.presence?.code;
  if (!survivorCode) throw new Error(`merge: no share code at users/${S}/presence/code — the survivor is not a usable merge target`);
  const gids = Object.keys(loser.groups || {});

  // --- loser-side residue: THE shared enumerator, never a local list ---------
  // Unconditional: every one of these is dead the moment the loser is, and a
  // null on a path that holds nothing is a no-op. Conditioning them on a read
  // is what let expunge and graduation drift over followerNames once already.
  // Canvases are the one exception (see the canvas block below) — they are
  // driven by the authoritative shallow key list so a forgotten canvasKeys
  // cannot silently delete a drawing that was never moved.
  for (const render of crossRefRenderers({ followers: loser.followers, following: loserPrefs?.following, groups: loser.groups, pendingInvites: loserPendingInvites })) {
    const path = render(L);
    if (path.startsWith('canvases/')) continue;
    writes[path] = null;
  }

  // --- followers / followerNames: union, survivor wins -----------------------
  for (const [follower, code] of Object.entries(loser.followers || {})) {
    // A survivor→loser or loser→loser edge is not a contact to keep: both ends
    // are about to stop existing, and writing one would land under a subtree
    // nulled wholesale below (the overlap graduation's doomed-target guard
    // exists for).
    if (follower === S || follower === L) continue;
    if (survivor.followers?.[follower] === undefined) {
      // `code` is the FOLLOWER's own share code — nothing about the loser — so
      // it moves verbatim.
      writes[`users/${S}/followers/${follower}`] = code;
      const fname = loser.followerNames?.[follower];
      if (fname !== undefined) writes[`users/${S}/followerNames/${follower}`] = fname;
    } else {
      conflict('contact-collapsed', `users/${S}/followers/${follower}`, `${follower} followed both accounts`, 'survivor entry kept');
    }
  }

  // --- following: union, survivor wins --------------------------------------
  for (const [followee, card] of Object.entries(loserPrefs?.following || {})) {
    if (followee === S || followee === L) continue;
    if (survivorPrefs?.following?.[followee] === undefined) {
      // The card is `{ code, label }` where code is the FOLLOWEE's and label is
      // the loser's private nickname — the same human's nickname, so it moves.
      writes[`userPrefs/${S}/following/${followee}`] = card;
    } else {
      conflict('contact-collapsed', `userPrefs/${S}/following/${followee}`, `both accounts followed ${followee}`, 'survivor entry kept');
    }
  }

  // --- notify prefs: union, survivor wins -----------------------------------
  for (const [contact, rec] of Object.entries(loserPrefs?.notify || {})) {
    if (contact === L) continue;
    if (survivorPrefs?.notify?.[contact] === undefined) writes[`userPrefs/${S}/notify/${contact}`] = rec;
  }

  // --- peer backrefs: repoint L → S, collapse where the peer had both -------
  const peers = new Set([
    ...Object.keys(loser.followers || {}),
    ...Object.keys(loserPrefs?.following || {}),
  ]);
  peers.delete(S);
  peers.delete(L);
  for (const peer of peers) {
    // peer follows L  →  peer follows S. The card's `code` is the field that
    // RESOLVES to an account, so it must become the survivor's; the `label` is
    // the peer's own private nickname for the human behind both accounts and
    // is theirs to keep.
    const peerFollowing = await deps.getVal(`userPrefs/${peer}/following/${L}`);
    if (peerFollowing !== null && peerFollowing !== undefined) {
      const already = await deps.getVal(`userPrefs/${peer}/following/${S}`);
      if (already === null || already === undefined) {
        writes[`userPrefs/${peer}/following/${S}`] = { code: survivorCode, label: peerFollowing?.label ?? '' };
      } else {
        conflict('contact-collapsed', `userPrefs/${peer}/following/${S}`, `${peer} followed both accounts`, 'survivor card kept');
      }
    }
    // L follows peer  →  S appears in the peer's followers. `followers/{uid}`
    // holds THAT uid's share code, so the repointed entry carries the
    // survivor's — the loser's would resolve to a uid that no longer exists.
    const backref = await deps.getVal(`users/${peer}/followers/${L}`);
    if (backref !== null && backref !== undefined) {
      const already = await deps.getVal(`users/${peer}/followers/${S}`);
      if (already === null || already === undefined) {
        writes[`users/${peer}/followers/${S}`] = survivorCode;
        // followerNames/{uid} is the name that uid publishes about itself, and
        // it is REPOINTED (spec §7's peer-backref row), not dropped. A name is
        // not a resolvable identifier: the code has to become the survivor's
        // because the loser's resolves to a uid that is about to stop existing,
        // whereas the published name belongs to the one human behind both
        // accounts, so carrying it across is lossless. Dropping it would
        // degrade every such peer to a bare code on every merge.
        const priorName = await deps.getVal(`users/${peer}/followerNames/${L}`);
        if (priorName !== null && priorName !== undefined) writes[`users/${peer}/followerNames/${S}`] = priorName;
      } else {
        conflict('contact-collapsed', `users/${peer}/followers/${S}`, `${peer} was followed by both accounts`, 'survivor entry kept');
      }
    }
  }

  // --- groups: union; survivor member record wins; ownership follows --------
  for (const gid of gids) {
    const [groupName, loserMember, survivorMember, ownerId] = await Promise.all([
      deps.getVal(`groups/${gid}/name`),
      deps.getVal(`groups/${gid}/members/${L}`),
      deps.getVal(`groups/${gid}/members/${S}`),
      deps.getVal(`groups/${gid}/ownerId`),
    ]);

    if (loserMember && (survivorMember === null || survivorMember === undefined)) {
      writes[`groups/${gid}/members/${S}`] = loserMember;
    } else if (loserMember && survivorMember) {
      conflict(
        'group-member-collision',
        `groups/${gid}/members/${S}`,
        `both accounts are members of ${groupName || gid}: "${loserMember.displayName ?? '—'}" vs "${survivorMember.displayName ?? '—'}"`,
        adopt.has(gid) ? "loser's displayName adopted" : "survivor's record kept",
      );
      if (adopt.has(gid) && loserMember.displayName !== undefined) {
        writes[`groups/${gid}/members/${S}/displayName`] = loserMember.displayName;
      }
      // Higher role wins: owner outranks member.
      if (loserMember.role === 'owner' && survivorMember.role !== 'owner') {
        writes[`groups/${gid}/members/${S}/role`] = 'owner';
      }
    }
    if (ownerId === L) writes[`groups/${gid}/ownerId`] = S;

    // Enumeration entry: keep the more recent visit.
    const loserEnum = loser.groups[gid];
    const survivorEnum = survivor.groups?.[gid];
    if (!survivorEnum) writes[`users/${S}/groups/${gid}`] = loserEnum;
    else if ((loserEnum?.lastVisited ?? 0) > (survivorEnum?.lastVisited ?? 0)) {
      writes[`users/${S}/groups/${gid}`] = loserEnum;
    }

    const pending = await deps.getVal(`pendingInvitesByGroup/${gid}/${L}`);
    if (pending !== null && pending !== undefined) writes[`pendingInvitesByGroup/${gid}/${S}`] = pending;
  }

  // --- identity: free the loser code (D1), move invite tokens ---------------
  const loserCode = loser.presence?.code;
  if (loserCode) writes[`codeIndex/${loserCode}`] = null;
  for (const [token, rec] of Object.entries(loser.invites || {})) {
    writes[`users/${S}/invites/${token}`] = rec;
    writes[`inviteIndex/${token}`] = { ownerPath: `users/${S}/invites/${token}`, ownerUid: S };
  }
  const loserLastSeen = loser.presence?.lastSeen;
  const survivorLastSeen = survivor.presence?.lastSeen;
  if (typeof loserLastSeen === 'number' && loserLastSeen > (survivorLastSeen ?? -Infinity)) {
    writes[`users/${S}/presence/lastSeen`] = loserLastSeen;
  }

  // --- push tokens: union, both devices stay reachable ----------------------
  for (const [token, rec] of Object.entries(loserTokens || {})) {
    writes[`pushTokens/${S}/${token}`] = rec;
  }
  writes[`pushTokens/${L}`] = null;

  // --- mailboxes (D3) — the loser side is already nulled by the enumerator --
  for (const box of DROP_MAILBOXES) {
    losses.push(`${box}/${L} dropped (transient)`);
  }
  /** @type {Record<string, any>} */
  const loserMailboxes = {};
  for (const box of UNION_MAILBOXES) {
    const own = await deps.getVal(`${box}/${L}`);
    loserMailboxes[box] = own;
    for (const [key, rec] of Object.entries(own || {})) {
      const already = await deps.getVal(`${box}/${S}/${key}`);
      if (already === null || already === undefined) {
        writes[`${box}/${S}/${key}`] = rec;
      } else {
        // D3 unions these BECAUSE they are real state, so a dropped one is a
        // real loss and has to be in the report the operator approves.
        conflict('mailbox-collision', `${box}/${S}/${key}`, `both accounts hold ${box} entry ${key}`, 'survivor entry kept');
        losses.push(`${box}/${L}/${key} dropped (the survivor already holds ${box}/${S}/${key})`);
      }
    }
  }
  // pendingInvites is dual-written with its by-group sweep index
  // (js/db/groups.ts) — moving one without the other is exactly the asymmetry
  // integrity.js flags. The SURVIVOR side is merge's own business and stays
  // here; the loser-side nulls come from the enumerator, which is handed the
  // same mailbox so it can reach the gids `groups` cannot see.
  for (const gid of Object.keys(loserMailboxes.pendingInvites || {})) {
    if (writes[`pendingInvites/${S}/${gid}`] !== undefined) writes[`pendingInvitesByGroup/${gid}/${S}`] = true;
  }

  // --- canvases (D2): sorted-pair keys, survivor wins, self-canvas deleted --
  for (const { peer, key } of canvasPeers(canvasKeys, L)) {
    if (peer === S || peer === L) {
      // A canvas BETWEEN the merging accounts (or a self-canvas) would become
      // canvases/{S}_{S} — deleted rather than moved.
      writes[`canvases/${key}`] = null;
      losses.push(`canvases/${key} deleted (canvas between the two merged accounts) — its strokes are lost`);
      continue;
    }
    const target = canvasKeyFor(S, peer);
    if (existingCanvases.has(target)) {
      conflict('canvas-collision', `canvases/${target}`, `both accounts have a canvas with ${peer}`, "survivor's drawing kept, loser's deleted");
      losses.push(`canvases/${key} deleted (collision with canvases/${target}) — its strokes are lost`);
    } else {
      // METADATA ONLY, and LEAF BY LEAF in both directions. Reading
      // canvases/${key} whole would pull the unbounded strokes node into an
      // update payload, so each carried child is read as its own leaf; writing
      // canvases/${target} whole would REPLACE that node, deleting the
      // survivor's strokes. The collision guard above cannot be trusted to
      // prevent that: canvasKeys is the one input that does not come from the
      // live re-read, so a canvas created between snapshot and preview is
      // absent from it and lands here. Writing leaves degrades that race from
      // "the survivor's drawing is destroyed" to "its bg is overwritten".
      for (const field of CANVAS_CARRIED) {
        const value = await deps.getVal(`canvases/${key}/${field}`);
        if (value !== null && value !== undefined) writes[`canvases/${target}/${field}`] = value;
      }
      losses.push(`canvases/${key} → canvases/${target}: settings carried, strokes NOT — the drawing is lost`);
    }
    writes[`canvases/${key}`] = null;
  }

  // --- telegram repoint: the SHARED link-write builder (§8.3) ----------------
  // Every write and every delete of a telegramUsers/{tgId} node goes through
  // telegram-link-write.js, which reads the node first. This block used to hand-copy
  // performLink's write list and never read telegramUsers at all, so it could
  // (a) delete a mapping belonging to a live third account while telling the
  // operator it deleted the loser's, (b) overwrite that same third account's
  // mapping with the survivor's uid raising no conflict whatsoever, and
  // (c) silently drop mapping fields performLink does not restate.
  /** @param {import('../telegram-link-write.js').LinkWriteResult} result */
  const foldLinkWrites = (result) => {
    Object.assign(writes, result.writes);
    conflicts.push(...result.conflicts);
    losses.push(...result.losses);
  };
  const loserLink = await deps.getVal(`telegramByUid/${L}`);
  if (opts.telegramRepoint) {
    if (!loserLink?.tgId) throw new Error(`merge: telegramRepoint requested but ${L} has no telegram link`);
    const tgId = String(loserLink.tgId);
    const survivorLink = await deps.getVal(`telegramByUid/${S}`);
    if (survivorLink?.tgId && String(survivorLink.tgId) !== tgId) {
      // The survivor's own prior mapping is torn down to make room — but only
      // if it is genuinely the survivor's; the builder refuses and names the
      // real owner when the reverse index points at a mapping someone else
      // holds. Its prefs are overwritten by the link writes below either way.
      const priorTgId = String(survivorLink.tgId);
      const teardown = await buildMappingTeardown(deps, { tgId: priorTgId, owner: S, context: `replaced by ${L}'s Telegram on this merge` });
      conflict('telegram-relink', `telegramByUid/${S}`, `survivor already holds tgId ${priorTgId}`, 'its mapping is dropped and replaced by the loser tgId');
      foldLinkWrites(teardown);
      if (writes[`telegramUsers/${priorTgId}`] === null) {
        losses.push(`telegramUsers/${priorTgId} dropped (the survivor's prior Telegram link)`);
      }
    }
    // ownUids: a prior holder that is the loser or the survivor needs no
    // direct-relink reset — the loser's reverse index is nulled right here and
    // the survivor's prefs are overwritten by the link writes.
    foldLinkWrites(await buildLinkWrites(deps, {
      tgId, uid: S, now, fallbackChatId: loserLink.chatId, ownUids: [L, S],
    }));
    writes[`telegramByUid/${L}`] = null;
  } else if (loserLink?.tgId) {
    // Without a repoint the mapping must still come down, or it points at a
    // uid that no longer exists and the next Mini App open bootstraps onto it.
    const tgId = String(loserLink.tgId);
    foldLinkWrites(await buildMappingTeardown(deps, { tgId, owner: L, context: `${L} is merged away into ${S}` }));
    writes[`telegramByUid/${L}`] = null;
    if (writes[`telegramUsers/${tgId}`] === null) {
      losses.push(`telegramUsers/${tgId} dropped (the loser's Telegram link is not repointed)`);
    }
  }

  // --- the loser's own subtrees go last: survivor prefs win wholesale -------
  writes[`users/${L}`] = null;
  writes[`userPrefs/${L}`] = null;
  losses.push(`userPrefs/${L} discarded (survivor's prefs win)`);

  return { writes, conflicts, losses };
}

/**
 * Apply a plan built by buildMergePlan. ONE atomic update, exactly like
 * graduation — a crash cannot half-merge. rootUpdate drops the previewed nulls
 * that sit under an already-nulled ancestor, so the wire payload is a subset of
 * plan.writes and nothing else about it differs.
 * @param {{ update: (path: string, writes: Record<string, unknown>) => Promise<unknown> }} deps
 * @param {import('./types.js').WritePlan} plan
 */
export async function applyMergePlan(deps, plan) {
  await rootUpdate(deps, plan.writes);
}
